---

name: metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: none
          config_timezone: Europe/Lisbon
          config_twemoji: yes
          config_octicon: yes
          config_display: columns
          plugin_calendar: yes
          plugin_calendar_limit: 0
          plugin_traffic: yes
          repositories_forks: yes
          repositories: 500
          repositories_affiliations: owner,collaborator,organization_member
          base_indepth: yes
          config_output: insights
          optimize: css, xml, svg
          experimental_features: --optimize-svg
          debug_print: yes
      # Deploy
      - uses: actions/setup-python@v3
      - name: Deploy
        run: |
          pip install virtualenv
          virtualenv venv -ppython3
          venv/bin/pip install markdown-to-presentation
          mkdir -p dist
          cp /metrics_renders/github-metrics.html dist/index.html
          cd dist
          ../venv/bin/markdown-to-presentation push \
            --default-branch master \
            --pages-branch deploy \
            index.html
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
